/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ittapiros;

import java.awt.GridLayout;
import java.util.Random;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Banyek
 */
public class felulet extends javax.swing.JFrame {

    /**
     * Creates new form felulet
     */
    public felulet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pohar1 = new javax.swing.JButton();
        pohar2 = new javax.swing.JButton();
        pohar3 = new javax.swing.JButton();
        hely = new javax.swing.JCheckBox();
        talaltE = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ujJatek = new javax.swing.JMenuItem();
        ment = new javax.swing.JMenuItem();
        betolt = new javax.swing.JMenuItem();
        pohar4 = new javax.swing.JMenu();
        pohar3Valaszt = new javax.swing.JMenuItem();
        pohar4Valaszt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pohar1.setText("1. pohár");

        pohar2.setText("2. pohár");

        pohar3.setText("3. pohar");

        hely.setText("Új hely");
        hely.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helyActionPerformed(evt);
            }
        });

        talaltE.setText("Talált/Nem talált");

        jMenu1.setText("Fájl");

        ujJatek.setText("Új játék");
        ujJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujJatekActionPerformed(evt);
            }
        });
        jMenu1.add(ujJatek);

        ment.setText("Mentés");
        ment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentActionPerformed(evt);
            }
        });
        jMenu1.add(ment);

        betolt.setText("Betöltés");
        jMenu1.add(betolt);

        jMenuBar1.add(jMenu1);

        pohar4.setText("Játék");

        pohar3Valaszt.setText("3 pohár");
        pohar4.add(pohar3Valaszt);

        pohar4Valaszt.setText("4 pohár");
        pohar4Valaszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pohar4ValasztActionPerformed(evt);
            }
        });
        pohar4.add(pohar4Valaszt);

        jMenuBar1.add(pohar4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hely)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(talaltE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pohar1)
                                .addGap(45, 45, 45)
                                .addComponent(pohar2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(pohar3)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pohar1)
                    .addComponent(pohar2)
                    .addComponent(pohar3))
                .addGap(53, 53, 53)
                .addComponent(talaltE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(hely)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pohar4ValasztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pohar4ValasztActionPerformed
        int valasz = JOptionPane.showConfirmDialog(null,
                "Figyelem! Ez a mód jelenleg még nem elérhető!",
                "Figyelmeztetés", JOptionPane.DEFAULT_OPTION);
    }//GEN-LAST:event_pohar4ValasztActionPerformed

    private void mentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentActionPerformed
        if(hely.isSelected()){
            hol=rnd.nextInt(3)+1;
        }
    }//GEN-LAST:event_mentActionPerformed

    private void ujJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujJatekActionPerformed
        Random rnd= new Random();
        System.out.println(hol);
        //pohar1="";
    }//GEN-LAST:event_ujJatekActionPerformed

    private void helyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helyActionPerformed
        
    }//GEN-LAST:event_helyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(felulet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new felulet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem betolt;
    private javax.swing.JCheckBox hely;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem ment;
    private javax.swing.JButton pohar1;
    private javax.swing.JButton pohar2;
    private javax.swing.JButton pohar3;
    private javax.swing.JMenuItem pohar3Valaszt;
    private javax.swing.JMenu pohar4;
    private javax.swing.JMenuItem pohar4Valaszt;
    private javax.swing.JLabel talaltE;
    private javax.swing.JMenuItem ujJatek;
    // End of variables declaration//GEN-END:variables
   private Random rnd;
   private int hol=rnd.nextInt(3)+1;
}
